services:
  copyarr:
    image: ghcr.io/swamp2k/copyarr:latest
    container_name: copyarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - /mnt/user/appdata/copyarr:/data
      - /mnt/user/appdata/copyarr/config:/config
      - /mnt/user/media/downloads:/downloads
